-- 用户（Users）主表：通用迁移（适用于 local/H2 及默认/PostgreSQL 路径）
-- 说明：使用 ANSI/PG 兼容的 IDENTITY 语法与 TIMESTAMP，避免仅限 MySQL 的 AUTO_INCREMENT/TIMESTAMP 变体。

CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(64) NOT NULL,
  email VARCHAR(255) NOT NULL,
  phone VARCHAR(32) NOT NULL,
  password_hash VARCHAR(255) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 唯一索引（用户名、邮箱）
CREATE UNIQUE INDEX IF NOT EXISTS users_username_uq ON users(username);
CREATE UNIQUE INDEX IF NOT EXISTS users_email_uq ON users(email);