-- 创建帖子评论表 posts（平铺评论 + 一层回复）
-- 字段：id、thread_id、author_id、content_md、reply_to_post_id、created_at、updated_at、status
-- 约束：reply_to_post_id 允许为空；仅允许一层回复（由业务层校验）；
-- 索引：thread_id + created_at（正序分页）、reply_to_post_id

CREATE TABLE IF NOT EXISTS posts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  thread_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  content_md TEXT NOT NULL,
  reply_to_post_id BIGINT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL'
);

-- 外键约束（为简化迁移与导入，这里不启用级联删除）
-- 为兼容 local/H2 环境，移除对 threads/users 的外键约束（这些表可能在本路径未创建）
-- 如需在生产库启用外键，请使用 mysql 路径的迁移脚本
-- 保留自引用约束可在业务层面保证一致性，这里不添加数据库级约束以避免 H2 失败

-- 索引：按 created_at 正序分页读取指定 thread 的评论
CREATE INDEX IF NOT EXISTS idx_posts_thread_created ON posts(thread_id, created_at);
-- 索引：按楼中楼父评论查询
CREATE INDEX IF NOT EXISTS idx_posts_reply_parent ON posts(reply_to_post_id);