-- 主题帖主表：通用迁移（适用于 local/H2 及默认/PostgreSQL 路径）
-- 说明：使用 ANSI/PG 兼容的 IDENTITY 语法；移除 MySQL 专属的
--       AUTO_INCREMENT、ON UPDATE 等；不在此处启用外键以避免本路径
--       缺表导致的迁移失败。业务层仍会校验关联关系。

CREATE TABLE IF NOT EXISTS threads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  section_id BIGINT NOT NULL,
  author_id BIGINT NOT NULL,
  title VARCHAR(256) NOT NULL,
  content_md TEXT NOT NULL,
  spoiler BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL DEFAULT 'NORMAL',
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- 索引：按分区与创建时间分页
CREATE INDEX IF NOT EXISTS idx_threads_section_created ON threads(section_id, created_at);
-- 索引：按作者与更新时间分页
CREATE INDEX IF NOT EXISTS idx_threads_author_updated ON threads(author_id, updated_at);
-- 索引：按作者与创建时间分页
CREATE INDEX IF NOT EXISTS idx_threads_author_created ON threads(author_id, created_at);