-- 分区（Sections）主表：通用迁移（适用于 local/H2 及默认/PostgreSQL 路径）
-- 说明：使用 ANSI/PG 兼容的 IDENTITY 语法，避免仅限 MySQL 的 AUTO_INCREMENT；
--      时间字段使用 TIMESTAMP，默认 CURRENT_TIMESTAMP，以兼容 H2/PostgreSQL。

CREATE TABLE IF NOT EXISTS sections (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  slug VARCHAR(128) NOT NULL,
  description TEXT NULL,
  rules TEXT NULL,
  visible BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT sections_slug_uq UNIQUE (slug)
);

-- 辅助索引：按名称检索
CREATE INDEX IF NOT EXISTS idx_sections_name ON sections(name);