CREATE TABLE IF NOT EXISTS user_connected_accounts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id BIGINT NOT NULL,
  provider VARCHAR(32) NOT NULL,
  external_id VARCHAR(255),
  display_name VARCHAR(255),
  linked_at TIMESTAMP,
  CONSTRAINT fk_user_connected_accounts_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_connected_accounts_user_provider
  ON user_connected_accounts(user_id, provider);

CREATE UNIQUE INDEX IF NOT EXISTS uk_user_connected_accounts_provider_external
  ON user_connected_accounts(provider, external_id);
